App\Entity\Service:
    service{1..100}:
        title: <word()>
        description: <join($fake('paragraphs'), "\n\n")>
        user: "@user*"
        category: "@category*"
        locations: ["@location*"]
