security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 4

    providers:
        doctrine:
            entity:
                class: App:User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                login_path: security.login
                check_path: security.login
                username_parameter: email
                password_parameter: password
                provider: doctrine
                csrf_parameter: _csrf_security_token
            logout:
                path: logout
            remember_me:
                secret: "%secret%"
                always_remember_me: true
