# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.user_controller:
        class: AppBundle\Controller\UserController
        arguments: [ @doctrine.orm.entity_manager ]
