# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.abstract_controller:
        class: App\Controller\AbstractController
        abstract: true
        calls:
            - [setFormFactory, ["@form.factory"]]
            - [setEm, ["@doctrine.orm.entity_manager"]]
            - [setRouter, ["@router"]]
            - [setPaginator, ["@knp_paginator"]]
            - [setTokenStorage, ["@security.token_storage"]]
            - [setSession, ["@session"]]
            - [setAuthenticationUtils, ["@security.authentication_utils"]]
    app.user_controller:
        class: App\Controller\UserController
        parent: app.abstract_controller
        arguments:
            - "@app.user_manager"
    app.home_controller:
        class: App\Controller\HomeController
    app.registration_controller:
        class: App\Controller\RegistrationController
        parent: app.abstract_controller
        arguments:
            - "@app.user_manager"
    app.security_controller:
        class: App\Controller\SecurityController
        parent: app.abstract_controller
    app.service_controller:
        class: App\Controller\ServiceController
        parent: app.abstract_controller
        arguments:
            - "@app.service_manager"

    app.user_repository:
        class: App\Repository\UserRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - App:User
        calls:
            - [setPaginator, ["@knp_paginator"]]
    app.service_repository:
        class: App\Repository\ServiceRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - App:Service
        calls:
            - [setPaginator, ["@knp_paginator"]]
    app.repository.location_repository:
        class: App\Repository\LocationRepository
        arguments: [ "@doctrine.orm.entity_manager" ]

    app.form.no_validate_extension:
        class: App\Form\Extension\NoValidateExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
    app.form.type.filter_type:
        class: App\Form\Type\FilterType
        calls:
            - [ setLocationRepository, [ "@app.repository.location_repository" ] ]
        tags:
            - { name: form.type, alias: filter }
    app.form.type.login:
        class: App\Form\Type\LoginType
        tags:
            - { name: form.type, alias: login }

    app.listener.user_listener:
        class: App\Listener\RawUserPasswordEncoder
        arguments: ["@security.password_encoder"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    app.user_manager:
        class: App\Manager\UserManager
        arguments:
            - "@app.user_repository"
            - "@security.password_encoder"
    app.service_manager:
        class: App\Manager\ServiceManager
        arguments:
            - "@app.service_repository"

    app.service_voter:
        class: App\Security\ServiceVoter
        tags:
            - { name: security.voter }
        public: false

    faker.provider.util:
        class: App\DataFixtures\Faker\Provider\UtilProvider
        tags:
            - { name: hautelook_alice.faker.provider }
