# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.abstract_controller:
        class: AppBundle\Controller\AbstractController
        abstract: true
        calls:
            - [setFormFactory, [@form.factory]]
            - [setEm, [@doctrine.orm.entity_manager]]
            - [setRouter, [@router]]
            - [setPaginator, [@knp_paginator]]
            - [setTokenStorage, [@security.token_storage]]
            - [setSession, [@session]]
            - [setAuthenticationUtils, [@security.authentication_utils]]
            - [setPasswordEncoder, [@security.password_encoder]]
    app.user_controller:
        class: AppBundle\Controller\UserController
        parent: app.abstract_controller
        arguments:
            - @app.user_repository
    app.home_controller:
        class: AppBundle\Controller\HomeController
    app.registration_controller:
        class: AppBundle\Controller\RegistrationController
        parent: app.abstract_controller
        arguments:
            - @app.user_repository
    app.security_controller:
        class: AppBundle\Controller\SecurityController
        parent: app.abstract_controller
    app.service_controller:
        class: AppBundle\Controller\ServiceController
        parent: app.abstract_controller
        arguments:
            - @app.service_repository

    app.user_repository:
        class: AppBundle\Repository\UserRepository
        factory: [@doctrine.orm.entity_manager, getRepository]
        arguments:
            - App:User
    app.service_repository:
        class: AppBundle\Repository\ServiceRepository
        factory: [@doctrine.orm.entity_manager, getRepository]
        arguments:
            - App:Service
