# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.user_controller:
        class: AppBundle\Controller\UserController
        arguments:
            - @doctrine.orm.entity_manager
            - @knp_paginator
            - @form.factory
            - @router
    app.home_controller:
        class: AppBundle\Controller\HomeController
    app.registration_controller:
        class: AppBundle\Controller\RegistrationController
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @session
            - @router
            - @security.token_storage
    app.security_controller:
        class: AppBundle\Controller\SecurityController
        arguments:
            - @form.factory
            - @router
            - @security.authentication_utils
    app.service_controller:
        class: AppBundle\Controller\ServiceController
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @router
            - @knp_paginator
