# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.abstract_controller:
        class: AppBundle\Controller\AbstractController
        abstract: true
        calls:
            - [setFormFactory, [@form.factory]]

    app.user_controller:
        class: AppBundle\Controller\UserController
        arguments:
            - @doctrine.orm.entity_manager
            - @knp_paginator
            - @router
        parent: app.abstract_controller
    app.home_controller:
        class: AppBundle\Controller\HomeController
    app.registration_controller:
        class: AppBundle\Controller\RegistrationController
        arguments:
            - @doctrine.orm.entity_manager
            - @session
            - @router
            - @security.token_storage
        parent: app.abstract_controller
    app.security_controller:
        class: AppBundle\Controller\SecurityController
        arguments:
            - @router
            - @security.authentication_utils
        parent: app.abstract_controller
    app.service_controller:
        class: AppBundle\Controller\ServiceController
        arguments:
            - @doctrine.orm.entity_manager
            - @router
            - @knp_paginator
            - @security.token_storage
        parent: app.abstract_controller
