# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.abstract_controller:
        class: App\Controller\AbstractController
        abstract: true
        calls:
            - [setFormFactory, ["@form.factory"]]
            - [setEm, ["@doctrine.orm.entity_manager"]]
            - [setRouter, ["@router"]]
            - [setPaginator, ["@knp_paginator"]]
            - [setTokenStorage, ["@security.token_storage"]]
            - [setSession, ["@session"]]
            - [setAuthenticationUtils, ["@security.authentication_utils"]]
    app.user_controller:
        class: App\Controller\UserController
        parent: app.abstract_controller
        arguments:
            - "@app.user_repository"
            - "@app.user_manager"
    app.home_controller:
        class: App\Controller\HomeController
    app.registration_controller:
        class: App\Controller\RegistrationController
        parent: app.abstract_controller
        arguments:
            - "@app.user_repository"
    app.security_controller:
        class: App\Controller\SecurityController
        parent: app.abstract_controller
    app.service_controller:
        class: App\Controller\ServiceController
        parent: app.abstract_controller
        arguments:
            - "@app.service_repository"

    app.user_repository:
        class: App\Repository\UserRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - App:User
    app.service_repository:
        class: App\Repository\ServiceRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - App:Service

    app.form.no_validate_extension:
        class: App\Form\Extension\NoValidateExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    app.listener.user_listener:
        class: App\Listener\RawUserPasswordEncoder
        arguments: ["@security.password_encoder"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    app.user_manager:
        class: App\Manager\UserManager
        arguments:
            - "@app.user_repository"
            - "@security.password_encoder"
